# Generated by Django 3.2.9 on 2022-09-05 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0002_alter_instructor_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonapps.course'),
        ),
    ]
