# Generated by Django 3.2.9 on 2022-09-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0003_alter_instructor_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ManyToManyField(to='commonapps.Course'),
        ),
    ]
