# Generated by Django 3.2.9 on 2022-10-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0003_auto_20221027_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='submitted_users',
        ),
    ]
