# Generated by Django 3.2.9 on 2022-10-27 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonapps', '0004_remove_module_submitted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='submitted_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
