# Generated by Django 3.2.9 on 2022-09-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0004_auto_20220905_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.AddField(
            model_name='answers',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonapps.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
