# Generated by Django 3.2.9 on 2022-09-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0006_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
