# Generated by Django 3.2.9 on 2022-09-06 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commonapps', '0008_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerscores',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonapps.answers'),
        ),
        migrations.AlterField(
            model_name='learnerscores',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
