# Generated by Django 3.2.9 on 2022-10-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0005_module_submitted_users'),
        ('accounts', '0004_alter_customuser_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='track',
        ),
        migrations.AddField(
            model_name='customuser',
            name='intrest',
            field=models.ManyToManyField(blank=True, null=True, to='commonapps.Course'),
        ),
    ]
