# Generated by Django 3.2.9 on 2022-10-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221028_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='intrest',
            new_name='interest',
        ),
    ]
