# Generated by Django 3.2.9 on 2023-01-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0009_alter_learnerscores_answers'),
        ('accounts', '0007_auto_20230115_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='track',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonapps.track'),
        ),
    ]
