# Generated by Django 3.2.9 on 2023-01-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commonapps', '0009_alter_learnerscores_answers'),
        ('accounts', '0008_customuser_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commonapps.track'),
        ),
    ]
